/**
 * stratum-endpoint — the service that owns the address hardware miners dial.
 *
 * ══════════════════════════════════════════════════════════════════════════════════════════════
 * WHY THIS EXISTS
 *
 * `GET /v1/pool` reports `stratumEndpoint: null`, so `pool-web` tells a visitor to contact the
 * administrator. That is honest: the stratum ports are bound to loopback and raw TCP cannot
 * traverse the Cloudflare Tunnel (cloudflared carries HTTP(S); arbitrary TCP is Spectrum, an
 * enterprise product). Browser mining works over `wss://` and hardware miners have no route.
 *
 * With a NAT rule from the router to this host, the route exists. What does not exist is anything
 * keeping the ADVERTISED address true when the ISP moves it — and a stale endpoint is worse than
 * no endpoint, because firmware is configured against it and retries hard. See `observe.ts`.
 *
 * ══════════════════════════════════════════════════════════════════════════════════════════════
 * WHAT IT TOUCHES, AND WHAT IT DELIBERATELY DOES NOT
 *
 * Writes ONE generated file — `compose/generated/stratum.env`, holding `CF_STRATUM_PUBLIC_HOST` —
 * and recreates ONE service. It is not a deployer:
 *
 *   · NOT `release-deploy.sh`, which redeploys the estate. A WAN address changing must not be able
 *     to roll every container in the estate.
 *   · NOT a bare `docker compose up`, which drops `mainnet.env` and degrades public hostnames to
 *     `localtest.me` (the deploy memo records that trap).
 *   · `up -d --no-deps pool` — one service, no dependency cascade.
 *
 * It never writes a secret. A WAN address is public by definition, which is why the file lives in
 * `compose/generated/` and not `compose/secrets/`.
 */

import { createServer } from 'node:http'
import { setTimeout as sleep } from 'node:timers/promises'
import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { dirname } from 'node:path'
import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import { decide, observePublicAddress } from './observe.ts'

const run = promisify(execFile)

const RESOLVERS = (process.env['STRATUM_IP_RESOLVERS'] ??
  'https://api.ipify.org,https://ifconfig.me/ip,https://icanhazip.com')
  .split(',')
  .map((s) => s.trim())
  .filter(Boolean)

const ENV_FILE = process.env['STRATUM_ENV_FILE'] ?? '/estate/compose/generated/stratum.env'
const COMPOSE_FILE = process.env['STRATUM_COMPOSE_FILE'] ?? '/estate/compose/docker-compose.estate.yml'
const PROJECT = process.env['STRATUM_COMPOSE_PROJECT'] ?? 'cloudsforge-estate'
const INTERVAL_MS = Number(process.env['STRATUM_INTERVAL_MS'] ?? 300_000)
const APPLY = process.env['STRATUM_APPLY'] !== 'false'

/**
 * The gate that makes running this service BEFORE the NAT rule exists harmless.
 *
 * Off by default. While off, the loop observes, counts and exports metrics, and writes NOTHING —
 * so the generated file stays absent, `pool` reads no `POOL_STRATUM_PUBLIC_HOST`, and the API goes
 * on reporting `stratumEndpoint: null`, which is the honest answer until a miner can actually
 * connect.
 *
 * That ordering matters more than it looks. `pool/src/env.ts` REFUSES TO BOOT when a public host
 * is set and no chain declares a `POOL_<CHAIN>_STRATUM_PUBLIC_PORT` — the two are meaningless
 * apart. So a service that published a host the moment it started would take the pool down on a
 * deployment where the ports had not been decided yet. Publishing is therefore something the
 * owner turns on once, deliberately, after `nc -vz <wan> 3334` answers from outside.
 */
const PUBLISH = process.env['STRATUM_PUBLISH'] === 'true'

const KEY = 'CF_STRATUM_PUBLIC_HOST'

/** Counters, exported on /metrics. Named so a change is visible after the fact, not only live. */
const counters = { changes: 0, refusals: 0, disagreements: 0, applyFailures: 0 }
let lastChangeAt = 0
let current: string | null = null

function log(level: string, msg: string, extra: Record<string, unknown> = {}): void {
  console.log(JSON.stringify({ time: new Date().toISOString(), level, service: 'stratum-endpoint', msg, ...extra }))
}

async function fetchText(url: string): Promise<string> {
  const res = await fetch(url, { signal: AbortSignal.timeout(10_000) })
  if (!res.ok) throw new Error(`HTTP ${res.status}`)
  return res.text()
}

/** Read the published value back from the file, so a restart does not re-apply what is already live. */
async function readPublished(): Promise<string | null> {
  try {
    const body = await readFile(ENV_FILE, 'utf8')
    const line = body.split('\n').find((l) => l.startsWith(`${KEY}=`))
    const value = line?.slice(KEY.length + 1).trim()
    return value ? value : null
  } catch {
    return null
  }
}

async function publish(address: string): Promise<void> {
  await mkdir(dirname(ENV_FILE), { recursive: true })
  // Generated, and it says so: the next person to find this file must not hand-edit it.
  await writeFile(
    ENV_FILE,
    `# Generated by stratum-endpoint (micro-org#457). Do not edit — it is rewritten when the\n` +
      `# public address changes, and a hand-edit is silently reverted on the next observation.\n` +
      `${KEY}=${address}\n`,
    'utf8',
  )
}

async function recreatePool(): Promise<void> {
  // One service, no dependency cascade. See the header for what this deliberately is not.
  await run('docker', ['compose', '-p', PROJECT, '-f', COMPOSE_FILE, 'up', '-d', '--no-deps', 'pool'], {
    timeout: 180_000,
  })
}

async function tick(): Promise<void> {
  const observed = await observePublicAddress(RESOLVERS, fetchText)
  if (observed.kind === 'disagreed') counters.disagreements += 1

  const published = current ?? (await readPublished())
  const decision = decide(observed, published)

  if (decision.kind === 'keep') {
    current = published
    return
  }

  if (decision.kind === 'refuse') {
    counters.refusals += 1
    // WARN, not ERROR: refusing is this service working correctly. The live value is untouched.
    log('warn', 'refusing to republish the stratum endpoint; the previous value stands', {
      reason: decision.reason,
      published,
    })
    return
  }

  if (!PUBLISH) {
    // Watching, not publishing. Recorded at info because it is the intended state before the NAT
    // rule exists, and because an operator turning STRATUM_PUBLISH on wants to see what it WOULD
    // have written first.
    log('info', 'observed a new public address; not publishing (STRATUM_PUBLISH is not true)', {
      from: decision.previous,
      to: decision.address,
    })
    current = decision.address
    counters.changes += 1
    lastChangeAt = Date.now()
    return
  }

  log('info', 'the public address changed; republishing the stratum endpoint', {
    from: decision.previous,
    to: decision.address,
  })
  await publish(decision.address)

  if (APPLY) {
    try {
      await recreatePool()
    } catch (err) {
      counters.applyFailures += 1
      // The file is written and the container is not yet reading it. Say so plainly: the endpoint
      // the API advertises is the OLD one until this succeeds, which is the safe direction but is
      // not the intended state.
      log('error', 'wrote the new address but could not recreate pool; it still serves the old one', {
        error: err instanceof Error ? err.message : String(err),
      })
      return
    }
  }

  current = decision.address
  counters.changes += 1
  lastChangeAt = Date.now()
}

function metrics(): string {
  return [
    '# HELP stratum_public_host_changes_total Times the advertised stratum address was republished.',
    '# TYPE stratum_public_host_changes_total counter',
    `stratum_public_host_changes_total ${counters.changes}`,
    '# HELP stratum_public_host_refusals_total Observations refused rather than published.',
    '# TYPE stratum_public_host_refusals_total counter',
    `stratum_public_host_refusals_total ${counters.refusals}`,
    '# HELP stratum_resolver_disagreement_total Rounds where resolvers did not agree.',
    '# TYPE stratum_resolver_disagreement_total counter',
    `stratum_resolver_disagreement_total ${counters.disagreements}`,
    '# HELP stratum_apply_failures_total Times the address was written but pool could not be recreated.',
    '# TYPE stratum_apply_failures_total counter',
    `stratum_apply_failures_total ${counters.applyFailures}`,
    '# HELP stratum_public_host_last_change_timestamp_seconds When the address last changed.',
    '# TYPE stratum_public_host_last_change_timestamp_seconds gauge',
    `stratum_public_host_last_change_timestamp_seconds ${Math.floor(lastChangeAt / 1000)}`,
    '# HELP stratum_public_host_known Whether an address is currently observed.',
    '# TYPE stratum_public_host_known gauge',
    `stratum_public_host_known ${current ? 1 : 0}`,
    '# HELP stratum_publishing Whether this service is allowed to write the endpoint (0 = watching only).',
    '# TYPE stratum_publishing gauge',
    `stratum_publishing ${PUBLISH ? 1 : 0}`,
    '',
  ].join('\n')
}

const server = createServer((req, res) => {
  if (req.url === '/metrics') {
    res.writeHead(200, { 'content-type': 'text/plain; version=0.0.4' })
    res.end(metrics())
    return
  }
  if (req.url === '/livez' || req.url === '/readyz') {
    res.writeHead(200, { 'content-type': 'application/json' })
    // `observed`, not `published`. They are the same value only when STRATUM_PUBLISH is on, and
    // a service whose entire purpose is refusing to advertise an address it cannot stand behind
    // must not use the word "published" for one it has deliberately withheld.
    res.end(JSON.stringify({ ok: true, observed: current, publishing: PUBLISH }))
    return
  }
  res.writeHead(404)
  res.end()
})

server.listen(Number(process.env['PORT'] ?? 4000), () => {
  log('info', 'stratum-endpoint started', {
    resolvers: RESOLVERS.length,
    intervalMs: INTERVAL_MS,
    publish: PUBLISH,
    apply: APPLY,
  })
})

for (;;) {
  try {
    await tick()
  } catch (err) {
    log('error', 'observation round failed', { error: err instanceof Error ? err.message : String(err) })
  }
  await sleep(INTERVAL_MS)
}
