/**
 * Cover images for seeded content, through micro-studio.
 *
 * ── THE OWNER'S ASK, AND WHAT IT ACTUALLY MEANS HERE ─────────────────────────
 *
 * "for the bootstrap generate them with ai flux 2 pro". Two paths satisfy that,
 * and which one is right depends on whether a FLUX 2 Pro image for the thing
 * already exists.
 *
 *   1. **It exists.** `market.mjs` lists the estate's own FLUX 2 Pro asset sets
 *      — `micro-brand`, `micro-emberkin-assets`, `micro-aetherholm-assets`,
 *      `micro-tessera-assets`, seven hundred-odd PNGs between them. The cover
 *      for a listing OF those assets is one of those assets. `adoptExisting`
 *      reads one and uploads it.
 *
 *   2. **It does not.** A seeded Foresight question has no artwork anywhere.
 *      `generateCover` asks studio for one, which reaches FLUX when a model is
 *      configured and the documented placeholder when it is not.
 *
 * ══════════════════════════════════════════════════════════════════════════════
 * **NO FLUX ASSET IN THIS TREE IS EVER WRITTEN, MOVED, OVERWRITTEN OR
 * REGENERATED BY THIS FILE.** `adoptExisting` opens a file for READING and
 * uploads a copy of the bytes. The source is not touched, and there is no code
 * path here that writes into `brand/`, `emberkin-assets/`, `aetherholm-assets/`,
 * `tessera-assets/` or `wallet-assets/` at all.
 *
 * `generateCover` never regenerates either, and that is enforced rather than
 * intended: it LISTS the kit's assets first and returns an existing one if there
 * is one. Bootstrap runs several times an hour, so a generate-first version
 * would spend real money on every pass and hand the same listing a different
 * picture each time.
 * ══════════════════════════════════════════════════════════════════════════════
 *
 * ── WHY THE FLUX HALF IS UNPROVEN, SAID PLAINLY ─────────────────────────────
 *
 * No FLUX image has been generated by this code, and none can be on this
 * deployment: `AZURE_FOUNDRY_ENDPOINT` and `AZURE_FOUNDRY_API_KEY` are both
 * UNSET on the running studio container, which `studio/src/env.ts` treats as a
 * supported mode — the service boots, reports `degraded` through a soft probe,
 * and serves the placeholder backend. So `generateCover` is wired, tested
 * against the placeholder, and has never reached a model. When a model is
 * deployed and those two variables are set, the same call produces FLUX art with
 * no change here.
 *
 * That is stated rather than glossed because a seeded page full of placeholder
 * tiles that everyone believes is FLUX output is worse than an empty one.
 *
 * ── IDEMPOTENCY ─────────────────────────────────────────────────────────────
 *
 * Property 1 of `estate-seed.mjs`. Both paths have it, by different mechanisms:
 *
 *   * `adoptExisting` gets it FREE from content addressing. Studio keys uploads
 *     on `(owner_subject, checksum)`, so re-uploading identical bytes returns
 *     the first asset with `deduplicated: true` and writes no second row.
 *   * `generateCover` gets it by listing the kit's assets before generating —
 *     which is the same line that enforces the permanence rule above.
 */

import fs from 'node:fs'
import path from 'node:path'
import { ROOT, SERVICES, api, note, skip, sleep } from './lib.mjs'

/** How long to wait for a generation to finish before giving up on it. */
const GENERATION_TIMEOUT_MS = 180_000
const POLL_INTERVAL_MS = 2_000

/**
 * The accent every seeded kit is built around: CloudsForge orange.
 *
 * From `brand/`'s own design system, and the same value `studio`'s tests use. A
 * seeded kit with an invented accent would produce artwork that does not belong
 * to this estate.
 */
const ACCENT = '#ff4d00'

/** Is studio reachable at all? Answered once, so a whole seeding run skips cleanly. */
let reachable = null

export async function studioReachable() {
  if (reachable !== null) return reachable
  try {
    const res = await fetch(`${SERVICES.studio.base}/livez`, {
      signal: AbortSignal.timeout(5_000),
    })
    reachable = res.ok
  } catch {
    reachable = false
  }
  return reachable
}

/**
 * Upload raw image bytes to studio and return the asset.
 *
 * Not `api()`, because that helper JSON-encodes its body and this one must send
 * the bytes untouched. Everything else — the bearer token, the timeout — matches.
 *
 * `visibility=public` is deliberate and is the whole reason the image will
 * render: a browser sends no `Authorization` header on an `<img src>`, so a
 * private asset is a broken image to every visitor who is not its owner. These
 * are cover images on public listings; public is the correct and intended state,
 * and studio requires it to be said rather than assumed.
 */
async function uploadBytes(token, bytes, contentType) {
  const url = `${SERVICES.studio.base}/v1/uploads?visibility=public`
  const res = await fetch(url, {
    method: 'POST',
    headers: {
      accept: 'application/json',
      'content-type': contentType,
      authorization: `Bearer ${token}`,
    },
    body: bytes,
    signal: AbortSignal.timeout(60_000),
  })
  const text = await res.text()
  let parsed
  try {
    parsed = JSON.parse(text)
  } catch {
    parsed = { raw: text.slice(0, 300) }
  }
  if (res.status !== 200 && res.status !== 201) {
    const reason = parsed?.error?.reason ?? parsed?.error?.code ?? res.status
    throw new Error(`studio refused the upload: ${reason}`)
  }
  return { asset: parsed.asset, deduplicated: res.status === 200 }
}

/**
 * Use an image that already exists in this tree as a cover.
 *
 * `relativePath` is resolved under the MONOREPO ROOT and is opened read-only.
 * The permanence rule is enforced by there being no write here at all, and by
 * the path being resolved and then checked to be inside the tree — a seeded
 * entry naming `../../etc/passwd` would otherwise be read and uploaded.
 */
export async function adoptExisting(token, relativePath) {
  if (!(await studioReachable())) return null

  const root = path.resolve(ROOT, '..')
  const absolute = path.resolve(root, relativePath)
  // Containment check. The seed data is ours, but a path that escapes the tree
  // is worth refusing on principle rather than on trust in the caller.
  if (!absolute.startsWith(root + path.sep)) {
    throw new Error(`${relativePath} resolves outside the tree`)
  }
  if (!fs.existsSync(absolute)) {
    note(`no image at ${relativePath}; leaving this one without a cover`)
    return null
  }

  const bytes = fs.readFileSync(absolute)
  const extension = path.extname(absolute).toLowerCase()
  const contentType =
    extension === '.png'
      ? 'image/png'
      : extension === '.webp'
        ? 'image/webp'
        : 'image/jpeg'

  // Studio reads the magic bytes and disregards this header; it is sent because
  // it is true, not because it decides anything.
  const { asset, deduplicated } = await uploadBytes(token, bytes, contentType)
  note(
    `cover ${deduplicated ? 'reused' : 'stored'} from ${relativePath} ` +
      `(${asset.actualWidth}x${asset.actualHeight}, ${asset.checksum.slice(0, 14)}…)`,
  )
  return asset
}

/**
 * Find the seeded brand kit of this name, or create it.
 *
 * `GET /v1/brand-kits` is listed first rather than creating and catching the
 * 409, because the 409 carries no id — recovering from it would need this list
 * call anyway, one round trip later and only on the path that matters.
 */
async function ensureKit(token, name, stylePrompt) {
  const existing = await api('studio', '/v1/brand-kits?limit=200', { token, expect: 200 })
  const found = (existing.body.brandKits ?? []).find((kit) => kit.name === name)
  if (found) return found

  const created = await api('studio', '/v1/brand-kits', {
    method: 'POST',
    token,
    body: { name, accent: ACCENT, stylePrompt },
    expect: 201,
  })
  return created.body.brandKit
}

/**
 * A generated cover for content that has no artwork anywhere.
 *
 * Returns the kit's EXISTING asset when there is one. See the file header: this
 * is the line that makes repeated bootstraps free and that keeps a FLUX asset
 * from ever being regenerated.
 */
export async function generateCover(token, options) {
  if (!(await studioReachable())) return null

  const { slug, stylePrompt, kind = 'banner' } = options
  const kit = await ensureKit(token, `seed:${slug}`, stylePrompt)

  const already = await api('studio', `/v1/brand-kits/${kit.id}/assets?limit=1`, {
    token,
    expect: 200,
  })
  const reused = (already.body.assets ?? [])[0]
  if (reused) {
    note(`cover reused for ${slug} (${reused.checksum.slice(0, 14)}…)`)
    return reused
  }

  // 202. The generation leaves the request here and runs in a leased job, so
  // this polls rather than waits on the socket.
  const accepted = await api('studio', `/v1/brand-kits/${kit.id}/generate`, {
    method: 'POST',
    token,
    body: { kind },
    expect: 202,
  })
  const jobId = accepted.body.job?.id
  if (!jobId) throw new Error('studio accepted a generation and named no job')

  const deadline = Date.now() + GENERATION_TIMEOUT_MS
  let job = null
  while (Date.now() < deadline) {
    await sleep(POLL_INTERVAL_MS)
    const polled = await api('studio', `/v1/jobs/${jobId}`, { token, expect: 200 })
    job = polled.body.job
    if (job.status === 'succeeded' || job.status === 'failed') break
  }
  if (!job || job.status !== 'succeeded') {
    // Not fatal to the seeding run. A question without a cover is a question;
    // a bootstrap that aborts because an image did not render is worse.
    note(
      `generation for ${slug} did not succeed (${job?.status ?? 'timed out'}` +
        `${job?.errorCode ? `: ${job.errorCode}` : ''}); leaving it without a cover`,
    )
    return null
  }

  const listed = await api('studio', `/v1/brand-kits/${kit.id}/assets?limit=1`, {
    token,
    expect: 200,
  })
  const asset = (listed.body.assets ?? [])[0]
  if (!asset) return null

  // Published explicitly, for the same reason the upload path passes
  // `visibility=public`: private is studio's default and a private cover is a
  // broken image to every visitor.
  await api('studio', `/v1/assets/${asset.id}/visibility`, {
    method: 'POST',
    token,
    body: { visibility: 'public' },
    expect: 200,
  })

  note(
    `cover generated for ${slug} on the ${job.backend} backend` +
      `${job.backend === 'placeholder' ? ' — NOT flux; no image model is configured' : ''}`,
  )
  return asset
}

/** Announce the backend once, so a run's output cannot be mistaken for FLUX art. */
export async function reportImageBackend() {
  if (!(await studioReachable())) {
    skip('studio is not reachable; seeded content will have no cover images')
    return
  }
  try {
    const { body } = await api('studio', '/v1/backend', { expect: 200 })
    if (!body.configured) {
      note(
        'studio has NO image model configured, so generated covers are the ' +
          'documented placeholder and not FLUX 2 Pro. Existing FLUX assets ' +
          'adopted from the tree are unaffected.',
      )
    } else {
      note(`studio image backend: ${body.model ?? 'unnamed'}`)
    }
  } catch {
    note('studio did not report its image backend')
  }
}
