#!/usr/bin/env python3
"""Does the LIVE tunnel ingress table match what policy.yml says about it?

    ./scripts/check-tunnel-ingress.py                 # read it from the connector
    ./scripts/check-tunnel-ingress.py --from a.json   # or from a saved capture

── WHY THIS EXISTS ──────────────────────────────────────────────────────────

`gateway/dynamic/policy.yml` used to say the `/internal` refusal existed in two
places, and called the edge copy "the FIRST ingress rule in every
cloudflared/config.*.yml, generated by cloudflared/gen.py and diffed by CI".

Every clause of that was true of a topology that had been replaced. The live
setup is ONE connector in `cf-edge` with a token-delivered ingress table; the
`config.*.yml` files describe four tunnels that do not run. `gen.py --check`
regenerates them in memory and diffs against DISK — it never compares them to
Cloudflare, so it passed while describing something that no longer existed
(micro-org#512).

That is the exact failure `surface-routes.py` check 4 is named for — A ROUTER
DESCRIBED IN PROSE IS NOT A ROUTER — one directory over, where check 4 could
not see it because it only reads `gateway/dynamic/*.yml`. This check closes
that gap by reading the thing itself.

── WHAT IT CAN AND CANNOT SEE ───────────────────────────────────────────────

The connector publishes its own running config on the metrics port, so this
needs NO Cloudflare credentials and no dashboard access — it asks the process
what it is doing rather than asking the control plane what it was told. The
limit of that: it sees the ingress table, not Cloudflare's WAF, Access, or page
rules, which sit in front of it and are invisible from here. A pass means the
ingress table is as described, not that nothing else is filtering.

It prints hostnames and service URLs, which are public by construction — a
hostname is in DNS and the services are loopback ports. It reads no secret and
there is none in this document to read.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys

NAMESPACE = "cloudsforge-estate"
METRICS = "http://cloudflared-metrics.cf-edge.svc.cluster.local:2000/config"

# The loopback ports the gateway listens on. A service outside this set is
# either a new surface nobody recorded or a leftover pointing at nothing.
KNOWN_ORIGINS = {"http://127.0.0.1:9081", "http://127.0.0.1:9181", "http_status:404"}

APEX = "cloudsforge.online"


def capture() -> dict:
    """The connector's own view, via any gateway pod that can reach it."""
    pods = subprocess.run(
        ["kubectl", "get", "pod", "-n", NAMESPACE, "-o", "name"],
        capture_output=True, text=True, check=True,
    ).stdout.split()
    gateway = next((p.split("/")[1] for p in pods if p.split("/")[1].startswith("gateway-")), None)
    if gateway is None:
        sys.exit(f"FATAL: no gateway pod in {NAMESPACE} to reach the connector from")
    out = subprocess.run(
        ["kubectl", "exec", "-n", NAMESPACE, gateway, "--", "wget", "-qO-", METRICS],
        capture_output=True, text=True, check=True,
    ).stdout
    if not out.strip():
        sys.exit("FATAL: the connector returned nothing — is cloudflared running in cf-edge?")
    return json.loads(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--from", dest="path", help="a saved /config capture, instead of the live one")
    args = ap.parse_args()

    doc = json.load(open(args.path)) if args.path else capture()
    ingress = doc.get("config", {}).get("ingress", [])
    version = doc.get("version", "?")

    findings: list[str] = []
    notes: list[str] = []

    print(f"tunnel config version {version}, {len(ingress)} ingress rules")

    # 1. Every origin is one we know. A rule pointing somewhere else is either an
    #    undocumented surface or residue, and both are worth a name.
    for rule in ingress:
        service = rule.get("service", "")
        if service not in KNOWN_ORIGINS:
            findings.append(
                f"ingress rule for {rule.get('hostname') or '(catch-all)'} points at {service}, "
                f"which is not one of the gateway's loopback origins"
            )

    # 2. No hostname from outside the estate. `savvanis.life` sat here for weeks
    #    pointing at a port nothing listens on — harmless, and exactly the kind of
    #    thing that is never noticed because nothing enumerates the table.
    for rule in ingress:
        host = rule.get("hostname")
        if host and not (host == APEX or host.endswith(f".{APEX}")):
            findings.append(f"ingress rule for {host}, which is not under {APEX}")

    # 3. THE CLAIM POLICY.YML MAKES. Reported, not enforced: adding it crosses to
    #    Cloudflare's side and is an owner action, so this states what is true
    #    rather than failing on a decision nobody has taken.
    with_path = [r for r in ingress if r.get("path")]
    if with_path:
        notes.append(f"{len(with_path)} path-matching rule(s) at the edge:")
        for rule in with_path:
            notes.append(f"    {rule.get('hostname') or '*'}  {rule['path']}  -> {rule.get('service')}")
    else:
        notes.append(
            "NO path-matching rules at the edge, so the /internal refusal is single-layer: "
            "cf-internal-refusal in gateway/dynamic/policy.yml is the only thing refusing it. "
            "That router is real and verified — see policy.yml — but policy.yml must not claim "
            "an edge copy while this line is printed. micro-org#512."
        )

    for note in notes:
        print(f"  {note}")

    if findings:
        print()
        for finding in findings:
            print(f"::error::{finding}")
        print(f"\n{len(findings)} finding(s).")
        return 1

    print("\nok — every ingress rule points at a known origin and names a hostname under the apex.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
