#!/usr/bin/env python3
"""The scrape list is rendered from the release, and it excludes what it must.

── WHAT THIS GUARDS ──────────────────────────────────────────────────────────

`prometheus/targets/services.yaml` was the literal string `[]` from the day the
telemetry plane was first deployed until 2026-08-09. The `cf-services` job read
it, so Prometheus scraped none of the estate's 48 deployed services and all
twenty alert rules — every money alert included — evaluated against no data
(micro-org#308). The file is now generated by `render-prometheus-targets.py`
from the release manifest, and the failure it replaced was silent in both
directions, so both directions are checked here.

TOO FEW is the original defect: an empty or partial list means nothing is
watched, and a green dashboard that is green because it is empty is
indistinguishable from a healthy estate.

TOO MANY is the defect the fix could introduce, and it is not a lesser one. A
target that cannot be scraped sits `down` for ever, and an operator who has
learned that some of the red on the target page is normal is an operator who will
not see the red that is not. The eighteen static front ends serve no `/metrics`
at all; the three services that gate `/metrics` behind a header token are scraped
by their own jobs, because Prometheus attaches credentials per job and not per
target, so emitting them here as well would produce a permanent 401 beside a
working scrape of the same service.

── HOW IT AVOIDS BEING A CHECK THAT CANNOT FAIL ──────────────────────────────

Every assertion below is DIFFERENTIAL or NEGATIVE. "The output contains
`money-svc`" passes against a renderer that emits every service in the manifest,
so it is paired with "the output does not contain `pretty-web`" — which only the
correct rule satisfies. The two exclusion rules are exercised by fixtures that
differ in exactly one property from an included service:

  * `pretty-web` differs from `money-svc` only in probing `/healthz` on 8080
    instead of `/readyz`. A renderer that keyed on `kind:` or on a name suffix
    would pass one of these tests and fail the other.
  * `gated-svc` is identical to `money-svc` in every respect the compose model
    can see, and differs only by appearing as a `static_configs` target in the
    fixture scrape config. A renderer with a hardcoded exclusion list cannot
    pass this.
  * `odd-port-svc` probes `/readyz` on 4021 and not 4000, and the emitted target
    must say 4021. This is `foresight` and `tessera` on the real estate, and
    assuming a uniform in-container 4000 would have produced two permanently
    down targets for two healthy services.

And the tier rule is checked by REMOVAL: the same manifest is rendered twice,
once with a complete tier map and once with one line deleted, and the second must
FAIL. A renderer that defaulted an unknown service to Tier 2 produces two
successful renders and fails here — which is the whole point, because a money
service silently held to a Tier-2 objective is the drift the `tier` label was
introduced to prevent.

── WHY FIXTURES RATHER THAN THE ESTATE FILES ─────────────────────────────────

The real base compose interpolates the estate's gitignored credentials, which CI
does not have. So this builds the smallest inputs that can express each bug and
runs the real renderer over them. `--compose-json` is fed a fixture document
rather than shelling out to `docker compose`, so this check needs no Docker and
no registry and cannot go red for a reason that is not this one.

Exit non-zero on failure, print nothing but the verdict on success.
"""
import json
import pathlib
import subprocess
import sys
import tempfile

HERE = pathlib.Path(__file__).resolve().parent
RENDER = HERE / "render-prometheus-targets.py"

MANIFEST = """\
version: "9.9.9"
generated: "2026-08-09T00:00:00.000Z"
generator: cfctl release
services:
  - name: money-svc
    repo: micro-money-svc
    kind: service
    image: ghcr.io/example/money-svc
    tag: "9.9.9"
    commit: "0000000000000000000000000000000000000000"
  - name: odd-port-svc
    repo: micro-odd-port-svc
    kind: service
    image: ghcr.io/example/odd-port-svc
    tag: "9.9.9"
    commit: "1111111111111111111111111111111111111111"
  - name: gated-svc
    repo: micro-gated-svc
    kind: service
    image: ghcr.io/example/gated-svc
    tag: "9.9.9"
    commit: "2222222222222222222222222222222222222222"
  - name: pretty-web
    repo: micro-pretty-web
    kind: web
    image: ghcr.io/example/pretty-web
    tag: "9.9.9"
    commit: "3333333333333333333333333333333333333333"
  - name: elsewhere-svc
    repo: micro-elsewhere-svc
    kind: service
    image: ghcr.io/example/elsewhere-svc
    tag: "9.9.9"
    commit: "4444444444444444444444444444444444444444"
absent:
"""

# `elsewhere-svc` is deliberately ABSENT from this document: a manifest entry
# that is profile-gated into another environment (`faucet` is testnet-only in its
# own type system) is not a missing service, and a renderer that emitted a target
# for it would point Prometheus at a hostname that does not resolve.
COMPOSE_MODEL = {
    "services": {
        "money-svc": {
            "environment": {"PORT": "4000"},
            "healthcheck": {
                "test": ["CMD-SHELL", "node -e \"fetch('http://127.0.0.1:4000/readyz')\""]
            },
        },
        "odd-port-svc": {
            "environment": {"PORT": "4021"},
            "healthcheck": {
                "test": ["CMD-SHELL", "node -e \"fetch('http://127.0.0.1:4021/readyz')\""]
            },
        },
        "gated-svc": {
            "environment": {"PORT": "4000"},
            "healthcheck": {
                "test": ["CMD-SHELL", "node -e \"fetch('http://127.0.0.1:4000/readyz')\""]
            },
        },
        # Identical to a backend in every way except the one that decides.
        "pretty-web": {
            "healthcheck": {
                "test": ["CMD-SHELL", "wget -q -O /dev/null http://127.0.0.1:8080/healthz"]
            },
        },
    }
}

PROMETHEUS_YML = """\
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: gated-svc
    http_headers:
      x-gated-token:
        files:
          - /etc/prometheus/secrets/gated_token
    static_configs:
      - targets: ["gated-svc:4000"]
"""

# EVERY MANIFEST ENTRY IS TIERED HERE, INCLUDING THE TWO THAT MUST NOT BE
# EMITTED. That is deliberate and it is what makes the exclusion tests mean
# something. The renderer refuses a service it cannot tier, so with `pretty-web`
# and `elsewhere-svc` missing from this map, a renderer that had lost the
# `/readyz` rule or the this-environment rule entirely would STILL refuse them —
# for the wrong reason — and both exclusion tests would go green over a renderer
# that no longer excludes anything.
TIERS = """\
money-svc: "1"
odd-port-svc: "2"
gated-svc: "2"
pretty-web: "2"
elsewhere-svc: "2"
"""


def fail(message):
    print(f"FAIL: {message}", file=sys.stderr)
    sys.exit(1)


# THE FIXTURES, CHECKED BEFORE THEY ARE TRUSTED. Each of the three assertions
# below is satisfied vacuously by an input that lost the thing it exercises — a
# fixture with no web service passes "no web service is emitted" while proving
# nothing, which is this repository's most-repeated defect.
if "/healthz" not in json.dumps(COMPOSE_MODEL):
    fail("the fixture has no /healthz health check, so the front-end exclusion proves nothing.")
if "gated-svc:4000" not in PROMETHEUS_YML:
    fail("the fixture scrape config names no gated target, so the own-job exclusion proves nothing.")
if "4021" not in json.dumps(COMPOSE_MODEL):
    fail("the fixture has no non-4000 service, so the port derivation proves nothing.")

with tempfile.TemporaryDirectory() as tmp:
    tmpdir = pathlib.Path(tmp)
    manifest = tmpdir / "9.9.9.yaml"
    compose_json = tmpdir / "compose.json"
    prom = tmpdir / "prometheus.yml"
    tiers = tmpdir / "tiers.yaml"
    manifest.write_text(MANIFEST)
    compose_json.write_text(json.dumps(COMPOSE_MODEL))
    prom.write_text(PROMETHEUS_YML)
    tiers.write_text(TIERS)

    def render(label, expect_failure=False):
        proc = subprocess.run(
            [
                sys.executable,
                str(RENDER),
                str(manifest),
                "--compose-json",
                str(compose_json),
                "--prometheus-yml",
                str(prom),
                "--tiers",
                str(tiers),
            ],
            capture_output=True,
            text=True,
        )
        if expect_failure:
            if proc.returncode == 0:
                fail(
                    f"the renderer SUCCEEDED on the {label} input and had to fail.\n"
                    f"{proc.stdout}"
                )
            return proc.stderr
        if proc.returncode != 0:
            fail(f"the renderer exited {proc.returncode} on the {label} input:\n{proc.stderr}")
        return proc.stdout

    out = render("complete")

    # The targets the render actually emits, and not the prose about them. The
    # header names every excluded service in a comment so that an operator
    # reading the file can see what was left out and why, and a substring search
    # for `pretty-web` matched that comment — which would let a renderer that
    # emitted every front end pass the exclusion test with its own documentation.
    targets = [
        line[len("- targets: [\"") : -len("\"]")]
        for line in out.split("\n")
        if line.startswith('- targets: ["')
    ]

    if sorted(targets) != ["money-svc:4000", "odd-port-svc:4021"]:
        fail(
            "the render emits the wrong target set.\n"
            f"       expected: ['money-svc:4000', 'odd-port-svc:4021']\n"
            f"       got:      {sorted(targets)}\n\n{out}"
        )

    # Named individually as well as as a set, so a failure says which rule broke
    # rather than only that something did.
    if "pretty-web:8080" in targets or any(t.startswith("pretty-web") for t in targets):
        fail("a static front end was emitted. It serves no /metrics and would sit down for ever.")
    if any(t.startswith("gated-svc") for t in targets):
        fail(
            "a service with its own credentialed job was emitted into the file_sd list too.\n"
            "       Prometheus attaches headers per job, so this target would 401 permanently\n"
            "       beside a working scrape of the same service."
        )
    if any(t.startswith("elsewhere-svc") for t in targets):
        fail(
            "a manifest entry this environment does not define was emitted. Prometheus would\n"
            "       be pointed at a hostname that does not resolve."
        )
    if "odd-port-svc:4021" not in targets:
        fail(
            "the port was not taken from the service's own health check. Assuming 4000 puts\n"
            "       two of the estate's real services (foresight, tessera) permanently down."
        )

    # The tier must reach the label, and it must be the RIGHT one. `tier: "1"`
    # appearing anywhere would pass a substring test against a renderer that
    # stamped every target Tier 1.
    if '    tier: "1"' not in out or '    tier: "2"' not in out:
        fail(f"both tiers must appear as labels; the SLO rules select on them.\n\n{out}")
    money_block = out.split('- targets: ["money-svc:4000"]')[1]
    if '    tier: "1"' not in money_block.split("- targets:")[0]:
        fail(f"money-svc is Tier 1 in the map and is not labelled Tier 1.\n\n{out}")

    # ── THE REMOVAL TEST ──────────────────────────────────────────────────────
    # A renderer that defaults an unknown service to Tier 2 renders this happily,
    # and a money service quietly gets an objective ten times looser than the one
    # 13-operational-model.md §8 sets for it. That must be a refusal.
    tiers.write_text('odd-port-svc: "2"\ngated-svc: "2"\n')
    stderr = render("tier-map-missing-money-svc", expect_failure=True)
    if "money-svc" not in stderr:
        fail(f"the refusal does not name the untiered service, so it is unactionable:\n{stderr}")

print("ok: the scrape list is rendered from the release and excludes what cannot be scraped")
