#!/usr/bin/env python3
"""No document prescribes an image-pinning overlay that no deploy path passes.

WHAT THIS GUARDS (micro-org#414)
--------------------------------
`compose/docker-compose.design.yml` pinned all seventy-four services at `2.5.4`
and `docs/releasing.md` step 3 told an operator to pass it to a hand-typed
`docker compose` on every testnet deploy. Testnet had not run 2.5.4 since
2026-08-08, because every deploy since had gone through `release-deploy.sh`,
which reads a release manifest and has never heard of that overlay.

So the file stopped being bumped the moment the deploy path moved, and nothing
noticed, because nothing that RUNS used it. The document went on prescribing it.
On 2026-08-11 somebody followed the document while applying a one-variable
change and rolled `mint` from `2026.08.21` back to `2.5.4` — seventeen releases,
about a hundred and forty commits — in under twelve seconds, with a green `up -d`
and a healthy container. The old migrator then ran against the live testnet
schema and reported `from: 7, to: 7, applied: []`, which is the only reason it
cost nothing.

A stale pin is invisible from inside the file that carries it: 2.5.4 is a
perfectly well-formed tag naming an image that really exists. What is detectable
is the DISCONNECT — a file that pins the estate's own images and that no deploy
path applies. That is what this checks, in the three places it can be written
down.

WHAT IT CHECKS
--------------
  1. Every tracked compose file that pins a `ghcr.io/cloudsforge-online/micro-*`
     image at a literal tag is NAMED IN CODE — the Makefile, or a shell entry
     point. A file that pins the estate's images and is reachable only by being
     typed out of a document is a rollback waiting to be typed.
  2. No tracked document prescribes `-f <overlay>` for such a file. Rule 1 is
     about the file existing; this one is about the sentence that sends an
     operator to it, and it names the document and the line, because that is
     where the mistake is read.
  3. Every `-f docker-compose*.yml` written anywhere tracked — document, compose
     header, script — names a file that exists. Deleting an overlay leaves its
     command behind in the headers that quoted it, and a command that names a
     missing file is one an operator will "fix" by finding something similar.

     All three rules fire on `-f <file>`, the imperative form, and never on a
     file merely NAMED in a sentence. That is the difference between prescribing
     a thing and recording it, and this repository's documents correct in place
     rather than deleting — the paragraph explaining why an overlay was removed
     has to be able to say its name.

     A command that begins `cd ../<repo>` is a command run in ANOTHER
     repository's checkout, and the bare names in it are that repository's:
     `docker-compose.hearth-seed.yml`'s header quotes `-f
     docker-compose.testnet.yml`, which is hearth's own file and is not supposed
     to be here. Those are read as a sibling's and skipped. A name written with a
     directory in front of it points back into this repository and is still
     checked, which is how those same headers have their own `-f` verified.

WHY `micro-*` AND NOT EVERY ghcr IMAGE
--------------------------------------
Because the failure is a service being moved off the release, and a release
manifest names exactly the `ghcr.io/cloudsforge-online/micro-<repo>` images. The
`hearth-node` pins in `docker-compose.miners.yml` are a chain node, are pinned to
a commit sha rather than a moving tag, and have a check of their own —
`check-hearth-pins-agree.py`. Widening this rule to cover them would duplicate
that check and refuse a file whose pins are correct by construction.

WHY TRACKED FILES ONLY
----------------------
`compose/docker-compose.release.yml` is the rendered overlay. It pins every
service at a digest, it is generated by `release-render.py` on every deploy, and
on a deploy host it is sitting in the working tree right now. It is also
untracked, and that is the difference this check reads: a pin that a deploy
writes is the deploy, and a pin somebody committed is a claim about a deploy.

Exit non-zero on failure, print nothing but the verdict on success.
"""
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

# The rendered overlay. Named, not discovered: it is legitimately absent from a
# clean checkout and legitimately present and unignorable on a deploy host.
GENERATED = {"docker-compose.release.yml"}

# `image: ghcr.io/cloudsforge-online/micro-<repo>:<tag>`, quoted or not. An
# interpolated tag is not a pin — it is whatever the env file says — so `${` in
# the tag is skipped below rather than matched here.
ESTATE_IMAGE = re.compile(
    r"""image:\s*['"]?(ghcr\.io/cloudsforge-online/micro-[a-z0-9-]+):([^\s'"}]+)"""
)

# `-f docker-compose.foo.yml`, with or without a directory in front of it. Tight
# on purpose: `-f` is an ordinary flag on half the commands in this repository
# (`grep -f`, `tar -f`, `curl -f`), and a loose pattern here would report those.
COMPOSE_F = re.compile(r"-f[= ]+(\S*docker-compose[A-Za-z0-9._-]*\.ya?ml)")

# A whole-line comment, in a shell script, a Makefile recipe (`\t@# …`) or a YAML
# header. An inline trailing comment is not stripped: the code on that line is
# still code.
COMMENT_LINE = re.compile(r"^\s*@?#")

# `cd ../hearth && docker compose …` — a command that runs in a sibling
# repository's checkout, so its bare filenames are that repository's.
SIBLING_REPO = re.compile(r"\bcd\s+\.\./[A-Za-z0-9._-]+")


def tracked(pattern):
    """Files git knows about, matching a pathspec. Sorted, absolute."""
    out = subprocess.run(
        ["git", "-C", str(ROOT), "ls-files", "-z", "--", pattern],
        capture_output=True,
        text=True,
    )
    if out.returncode != 0:
        sys.exit(
            "FAIL: `git ls-files` did not run, so this check cannot tell a committed pin "
            "from a rendered one. It refuses rather than guessing:\n       "
            + out.stderr.strip()
        )
    return sorted(ROOT / p for p in out.stdout.split("\0") if p)


def code_lines(text):
    """The lines of a file that are instructions rather than prose."""
    return [line for line in text.splitlines() if not COMMENT_LINE.match(line)]


def references(text):
    """Every `-f <compose file>` in a file: its line, as written, and whose it is.

    Read as COMMANDS rather than as lines. A four-overlay invocation is one
    command spread over five lines, and reading those lines separately is how the
    `cd ../hearth` standing in front of a bare filename stops being visible.

    Comment markers are stripped before the join, because in a compose header or
    a script the command is quoted inside a comment — and a command in a comment
    is a command somebody copies. A markdown document is read whole, fenced code
    blocks and all, for the same reason.
    """
    lines = [re.sub(r"^\s*@?#\s?", "", line) for line in text.splitlines()]
    index = 0
    while index < len(lines):
        start, block = index, [lines[index]]
        while block[-1].rstrip().endswith("\\") and index + 1 < len(lines):
            index += 1
            block.append(lines[index])
        joined = " ".join(part.rstrip().rstrip("\\") for part in block)
        sibling = bool(SIBLING_REPO.search(joined))
        for ref in COMPOSE_F.findall(joined):
            offset = next((n for n, line in enumerate(block) if ref in line), 0)
            yield start + offset + 1, ref, sibling
        index += 1


def estate_pins(text):
    """The `micro-*` images this file pins at a literal tag."""
    return {
        f"{image}:{tag}"
        for image, tag in ESTATE_IMAGE.findall(text)
        if "${" not in tag
    }


def review(files, code_text):
    """The verdict, over a mapping of repository-relative path -> text.

    A mapping rather than a directory, so the fixture below can hand these rules
    the three files that produced micro-org#414 and assert they are refused. A
    check whose own correctness is only ever exercised by the clean tree it
    passes on is a check that has never been seen to fail.

    Returns (complaints, how many compose files, how many `-f` references).
    """
    bad = []
    compose = {
        path.split("/")[-1]: text
        for path, text in files.items()
        if path.startswith("compose/") and path.count("/") == 1 and path.endswith(".yml")
    }
    present = set(compose) | GENERATED

    # ── 1. AN OVERLAY THAT PINS THE ESTATE, THAT NOTHING APPLIES ─────────────
    pinning = {name: estate_pins(text) for name, text in compose.items() if estate_pins(text)}
    for name, pins in sorted(pinning.items()):
        if name in code_text:
            continue
        bad.append(
            f"compose/{name} pins {len(pins)} estate image(s) — e.g. `{sorted(pins)[0]}` — and "
            f"no script or Makefile target passes it. Nothing that runs can keep it current, "
            f"so its pins are as old as the last person who remembered; applying it moves "
            f"every service it names off the release the manifest deployed."
        )

    # ── 2. AND THE SENTENCE THAT SENDS AN OPERATOR TO IT ─────────────────────
    # ── 3. AND A COMMAND THAT NAMES A FILE THAT IS GONE ──────────────────────
    prescribed = 0
    for path, text in files.items():
        for number, ref, sibling in references(text):
            name = pathlib.PurePosixPath(ref).name
            if sibling and "/" not in ref:
                continue
            prescribed += 1
            if name in pinning and name not in code_text and path.endswith(".md"):
                bad.append(
                    f"{path}:{number} prescribes `-f {ref}`, an overlay that pins the "
                    f"estate's own images and that no deploy path passes. An operator who "
                    f"follows this line deploys whatever that file was pinned at when it "
                    f"was last edited."
                )
            if name not in present:
                bad.append(
                    f"{path}:{number} names `-f {ref}`, which does not exist. A command that "
                    f"names a missing file is one somebody completes by finding the nearest "
                    f"thing that does."
                )

    return list(dict.fromkeys(bad)), len(compose), prescribed


# The three files as they stood on 2026-08-11, reduced to the lines that decide
# it: an estate file some script names, an overlay pinning the estate that none
# does, and the document sending an operator to both.
BROKEN = {
    "compose/docker-compose.estate.yml": "services:\n  mint:\n    build: ../mint\n",
    "compose/docker-compose.design.yml": (
        "services:\n  mint: { image: ghcr.io/cloudsforge-online/micro-mint:2.5.4 }\n"
    ),
    "docs/releasing.md": (
        "### 3. Testnet\n\n"
        "    docker compose -p cf-testnet \\\n"
        "      -f docker-compose.estate.yml \\\n"
        "      -f docker-compose.design.yml \\\n"
        "      up -d\n"
    ),
}
CODE = "BASE=${BASE:-compose/docker-compose.estate.yml}\n"


def self_test():
    """These rules refuse the thing they were written for, asserted by running them.

    Every predicate here is a regular expression over other people's prose, and
    the failure mode of a regular expression that stops matching is a check that
    passes. `check-secret-hygiene.py` spent an unknown number of commits exiting
    green over a target that had been blinded (micro-org#340).
    """
    bad, _, _ = review(BROKEN, CODE)
    assert len(bad) == 2, f"the 2026-08-11 tree was not refused as expected: {bad}"
    assert any("compose/docker-compose.design.yml pins 1" in line for line in bad), bad
    assert any("docs/releasing.md:5 prescribes" in line for line in bad), bad

    # And accepts the tree this repository now has: the overlay gone, and the
    # document naming only what a script passes.
    fixed = {k: v for k, v in BROKEN.items() if "design" not in k}
    fixed["docs/releasing.md"] = BROKEN["docs/releasing.md"].replace(
        "      -f docker-compose.design.yml \\\n", ""
    )
    bad, _, refs = review(fixed, CODE)
    assert not bad, f"the repaired tree was refused: {bad}"
    assert refs == 1, f"the repaired tree's one -f reference was not read: {refs}"

    # An interpolated tag is not a pin, and `grep -f` is not a compose overlay.
    assert not estate_pins("    image: ghcr.io/cloudsforge-online/micro-mint:${CF_TAG}\n")
    assert not COMPOSE_F.findall("grep -f patterns.txt")
    assert code_lines("# a\nb\n\t@# c\n") == ["b"], "comment stripping no longer works"


def main():
    self_test()

    compose_files = [p for p in tracked("compose/*.yml") if p.parent.name == "compose"]
    docs = tracked("*.md")
    code = tracked("Makefile") + tracked("*.sh") + tracked("scripts/*.sh")
    if not compose_files or not docs or not code:
        sys.exit(
            "FAIL: found no compose files, no documents or no scripts. This check reads "
            "tracked paths and something has moved; it refuses rather than passing over "
            "an empty set."
        )

    files = {
        str(path.relative_to(ROOT)): path.read_text() for path in docs + compose_files + code
    }
    code_text = "\n".join("\n".join(code_lines(path.read_text())) for path in code)
    bad, inspected, prescribed = review(files, code_text)

    if bad:
        print("FAIL: a document prescribes an overlay no deploy path passes", file=sys.stderr)
        for line in bad:
            print(f"  - {line}", file=sys.stderr)
        return 1

    print(
        f"ok: {inspected} compose file(s), none pinning an estate image that no deploy path "
        f"passes; {prescribed} `-f` reference(s) across {len(files)} tracked file(s) name a "
        f"file that exists"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
