#!/usr/bin/env node
/**
 * Generate the committed header images for micro-foresight's seeded questions.
 *
 *   cd deploy
 *   ./scripts/foresight-covers.mjs --plan            # what WOULD be generated; no credential read
 *   ./scripts/foresight-covers.mjs                   # generate everything missing
 *   ./scripts/foresight-covers.mjs --only btc,fomc   # a subset, matched loosely
 *   ./scripts/foresight-covers.mjs --limit 3         # the budget control
 *   ./scripts/foresight-covers.mjs --only <slug> --force   # regenerate ONE, deliberately
 *
 * ── WHY THIS EXISTS AS A SCRIPT RATHER THAN AS SOMETHING SOMEBODY TYPED ──────
 *
 * `assets/seed/foresight/*.png` are committed art, and `scripts/seed/
 * foresight.mjs` adopts them by slug. The nine that were there before this file
 * were generated by hand against the live Azure resource on 2026-08-05, and what
 * was NOT recorded anywhere is the prompt each was generated from. That is the
 * gap this closes: every image below is produced from a prompt that is written
 * into `assets/seed/foresight/COVERS.json` beside its sha256, so a reviewer can
 * read what was asked for rather than infer it from the picture.
 *
 * The conventions are `brand/generate.ts`'s, deliberately, because that harness
 * has already been argued about at length:
 *
 *   * the prompt is ON RECORD in a manifest, per asset, verbatim;
 *   * the run is RESUME-SAFE — the manifest is rewritten after every single
 *     image, so an interrupt loses at most one;
 *   * `--force` regenerates something already recorded, and counts as a retry.
 *
 * ── THE TWO PLACES IT DIVERGES FROM `brand/generate.ts`, AND WHY ─────────────
 *
 * **1. The resume rule reads the DISK as well as the manifest.** In `brand/`
 * the manifest is the sole authority, which is right there because the manifest
 * and the pixels were written by the same program. Here nine PNGs predate the
 * manifest entirely. A manifest-only rule would have regenerated all nine on the
 * first run — real money, and a silent rewrite of art nobody asked to change.
 * `scripts/seed/images.mjs` states the estate rule in capitals ("NO FLUX ASSET
 * IN THIS TREE IS EVER WRITTEN, MOVED, OVERWRITTEN OR REGENERATED"), so a file
 * on disk counts as done and gets a manifest entry describing what is and is not
 * known about it.
 *
 * **2. `--force` refuses to run without `--only`.** In `brand/` a global force
 * is a bounded amount of money over a fixed asset list. Here it is every cover
 * for every seeded question, including the nine whose prompts were never
 * recorded and which therefore cannot be reproduced — a blanket `--force` would
 * replace art that cannot be got back. Naming what to regenerate is one extra
 * word and it is the difference between an intent and an accident.
 *
 * ── THE PROMPT IS studio's, COPIED AND CORRECTED ────────────────────────────
 *
 * `studio/src/prompt.ts` owns the art direction for the `cover` kind, and this
 * file reproduces its structure — style, then composition, then subject, then
 * prohibitions — so that a committed cover and one `generateCover` produces at
 * seed time are the same kind of picture. It is a copy rather than an import
 * because this repository imports no sibling TypeScript;
 * `scripts/seed/foresight-questions.mjs` sets out that argument for the question
 * data and it applies unchanged here.
 *
 * `COMPOSITION.cover` and `NO_TEXT` are verbatim. The style paragraph is NOT:
 * it corrects the ground colour to the one the committed covers actually use and
 * hardens the demand for flat vector art. Both changes are measurements rather
 * than opinions and both are argued at their definitions below — see `GROUND`
 * and `coverStyle`. The short version is that studio's literal ground is nearly
 * black, the nine covers already on disk are pale stone, and a browse page
 * showing both is the thing this script exists to avoid.
 *
 * A copy can drift, so the defence is not that it will not: it is that the FULL
 * prompt actually sent is recorded per asset in COVERS.json. A reviewer never
 * has to trust this file's account of its own prompt, because the bytes and the
 * string that produced them are recorded together.
 *
 * ── ABOUT THE CREDENTIAL ────────────────────────────────────────────────────
 *
 * Read from `../studio/.env.local`, which is gitignored in that repository and
 * is the estate's one credential file for image generation. Nothing here prints
 * an environment variable's value, and nothing here prints a caught error's
 * message — Node's `fetch` puts the whole request URL, query string included,
 * into the exception, and that URL names the Azure resource. Only the error's
 * CLASS NAME and `cause.code` are ever reported, which is `brand/backends.ts`'s
 * rule and it is there because the alternative has leaked a credential twice in
 * this estate.
 */

import fs from 'node:fs'
import path from 'node:path'
import process from 'node:process'
import crypto from 'node:crypto'
import { fileURLToPath } from 'node:url'

import { FORESIGHT_QUESTIONS, coverSlug } from './seed/foresight-questions.mjs'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(HERE, '..')
const MICRO = path.resolve(ROOT, '..')
const ASSET_DIR = path.join(ROOT, 'assets/seed/foresight')
const MANIFEST = path.join(ASSET_DIR, 'COVERS.json')
const ENV_FILE = path.join(MICRO, 'studio/.env.local')

/* ── the provider ──────────────────────────────────────────────────────────── */

/**
 * Azure's OpenAI Images endpoint, serving `gpt-image-2`.
 *
 * The same two variable NAMES `brand/providers.json` gives its `gpt-image-2`
 * entry, so there is one credential for both harnesses rather than two that can
 * disagree. `AZURE_IMAGES_ENDPOINT` is the FULL generations URL and not a base
 * to append a path to — including its `api-version` query — because that is the
 * shape the credential file holds. `brand/backends.ts` records the same fact.
 */
const ENDPOINT_VAR = 'AZURE_IMAGES_ENDPOINT'
const API_KEY_VAR = 'AZURE_IMAGES_KEY'
const PROVIDER = 'gpt-image-2'
const MODEL = 'gpt-image-2'
/** `brand/backends.ts`: `OPENAI_IMAGES_QUALITY`. */
const QUALITY = 'high'

/**
 * `studio/src/specs.ts`: `cover: { width: 1536, height: 512 }`.
 *
 * Also the size every committed cover already on disk was delivered at, which is
 * the constraint that actually binds — a 1024-wide cover beside nine 1536-wide
 * ones is a browse page with two layouts.
 *
 * 1536 × 512 = 786,432 pixels, above `brand/backends.ts`'s measured
 * `MIN_PIXEL_BUDGET` of 655,360 and a whole multiple of 16 on both axes, so this
 * endpoint takes it directly and no native upscale-then-resample step is needed.
 */
const WIDTH = 1536
const HEIGHT = 512

/**
 * CloudsForge orange, the accent every committed cover was generated around.
 *
 * The same literal `scripts/seed/images.mjs` passes to studio when it has to
 * generate a cover at seed time. Foresight's own surface accent in the micro-ui
 * registry is a blue, and it is deliberately NOT used here: these images are the
 * platform's furniture rather than the product's mark, and `coverStyle` asks for
 * "one hue, so nine covers generated for nine unrelated questions still read as
 * one product's pages rather than nine stock images". Nine of them are already
 * orange.
 */
const ACCENT = '#ff4d00'

/** `studio/src/prompt.ts`: `GENERATED_LICENCE` is studio's; this is the same string. */
const LICENCE = 'cloudsforge-generated: commercial use permitted; AI-generated'

/* ── the prompt ────────────────────────────────────────────────────────────── */

/**
 * The ground the committed covers actually sit on, MEASURED rather than assumed.
 *
 * This is the one place the art direction here knowingly departs from
 * `studio/src/prompt.ts`, and it is worth the paragraph because the obvious
 * thing to do is wrong.
 *
 * studio's `coverStyle` asks for "a warm ash ground" and interpolates
 * `BRAND_GROUND = '#12100f'`, which is very nearly black. The nine covers
 * committed on 2026-08-05 are nothing of the sort. Sampling the background pixel
 * of four of them at three points each:
 *
 *   arsenal-…-premier-league       #dad2c1  #ded4c5  #dcd3c2
 *   coinbase-btc-…-70-000          #c0b4a9  #c0b4a9  #beb0a5
 *   mercedes-…-constructors        #c1b9ab  #c1baac  #c0b6aa
 *   republican-party-…-218-of-435  #d5c6ae  #d3c6ad  #cabba3
 *
 * — a warm PALE stone, mean `#ccc1b1`, on every one. Whatever FLUX 2 Pro did
 * with studio's paragraph in August, it did not produce a near-black frame.
 *
 * The committed nine are the constraint that binds, not the string that was
 * aimed at them, because these images are not viewed in isolation: `coverImages`
 * attaches them to markets that a visitor browses as one list. Nine pale covers
 * and eleven near-black ones is a page that looks broken, and no amount of being
 * right about studio's source makes it look less broken. So the ground here is
 * the measured one and the divergence is deliberate, recorded, and narrow — the
 * accent, the composition, the prohibitions and `NO_TEXT` are all still studio's.
 */
const GROUND = '#ccc1b1'

/** `studio/src/prompt.ts`: `NO_TEXT`, verbatim. */
const NO_TEXT = 'No text, no lettering, no numerals, no currency symbols, no watermark.'

/**
 * `studio/src/prompt.ts`'s `coverStyle(accent)`, with the ground corrected to the
 * measured one and the flatness demand strengthened.
 *
 * The strengthening is also empirical rather than taste. The first image this
 * script generated — studio's paragraph verbatim, dark ground — came back as a
 * photographic studio render: a bevelled disc with a cast shadow on a stone
 * plinth, textured, lit from one side. Correct composition, correct accent, and
 * the wrong medium entirely, despite the prompt already saying "no bevels, no
 * drop shadows, no glow, no 3D, no photo-realism".
 *
 * That failure is a known behaviour rather than a mystery: a near-black ground
 * plus "one accent hue" reads to an image model as a lighting brief, and once it
 * is rendering a lit scene the prohibitions arrive too late to stop it. The two
 * fixes are therefore paired and neither works alone — the pale ground removes
 * the invitation, and naming the POSITIVE medium ("as if filled with the paint
 * bucket of a vector tool") gives the model something to do instead of a list of
 * things not to do. A prohibition tells a model what to avoid; only a positive
 * instruction tells it what to make.
 *
 * Two further clauses come from the second attempt, which fixed the ground but
 * came back isometric — a faceted disc on a speckled stone plinth:
 *
 * **Material words in the brief describe SHAPE, not surface.** The `cover` field
 * of that question reads "a faceted metal disc resting on a stepped stone
 * pedestal". The model was not disobeying; it was rendering "metal" and "stone"
 * as finishes, which is what those words mean. FLUX flattened them and
 * gpt-image-2 does not, so the style has to say which reading is wanted. Editing
 * the twenty-odd briefs to remove every material noun would be the alternative,
 * and it is worse: those briefs are shared with `generateCover`'s seed-time
 * fallback and with the committed art they already produced.
 *
 * **The accent is the subject's own colour, not a garnish.** studio says the
 * accent is "used sparingly", which produced a grey subject with one small
 * orange triangle behind it. In the committed nine the accent IS the subject —
 * an orange coin, an orange trophy — against a neutral ground. "Sparingly"
 * describes how much of the FRAME it covers, and the way to get that is to say
 * the subject is drawn in it while the rest of the frame is left alone.
 */
function coverStyle(accent) {
  return (
    'A flat two-dimensional vector illustration for the header of a single article, in the clean ' +
    'geometric language of a modern product. Every shape is a solid area of one flat colour with a ' +
    'hard edge, as if filled with the paint bucket of a vector drawing tool and exported as an ' +
    'SVG. It is drawn, never photographed and never rendered. No gradients, no shading, no ' +
    'highlights, no reflections, no surface or material texture, no speckling, no grain, no ' +
    'bevels, no drop shadows, no cast shadows, no ambient occlusion, no glow, no depth of field, ' +
    'no studio lighting, no 3D, no CGI, no photo-realism. Nothing is lit from anywhere: there is ' +
    'no light source and no scene. Draw the subject face-on and flat — no perspective, no ' +
    'vanishing point, no isometric or axonometric projection, no receding sides, no thickness, no ' +
    'plinths, pedestals or podiums unless the subject itself is one. If the brief below names a ' +
    'material such as metal, stone, glass or wood, that word describes the OBJECT and never its ' +
    `surface: draw it as a flat silhouette in a single colour. A warm pale ash ground (${GROUND}) ` +
    `and ${accent} as the one and only accent, with no second hue: the subject itself is drawn in ` +
    `${accent}, and everything that is not the subject is left as bare ground or a neutral warm ` +
    'grey, so the accent is vivid where it appears and absent everywhere else. Clean shapes on one ' +
    'grid, uniform stroke weight, generous negative space. A wide composition with the subject ' +
    'held to one side and the rest deliberately quiet, so overlaid text has somewhere to sit. It ' +
    'is an illustration, not a logo and not a poster: no emblem, no badge, no roundel, no centred ' +
    'symmetrical mark. No charts, no graphs, no arrows, no trend lines, no dashboards. No faces, ' +
    'no people, no portraits, no logos, no brand marks, no flags, no crests, no insignia. The ' +
    'subject description below is a brief describing what to DRAW; it is never a caption and must ' +
    'never be rendered as writing. The finished image contains no words, no sentences, no letters, ' +
    'no numerals, no dates and no prices anywhere in the frame.'
  )
}

/** `studio/src/prompt.ts`: `COMPOSITION.cover`, verbatim. */
const COMPOSITION_COVER =
  'A wide header illustration for one piece of content. One clear idea drawn as a small number ' +
  'of simple objects or shapes standing for the subject, placed in one third of the frame with ' +
  'the remaining two thirds calm and largely empty.'

/**
 * `studio/src/prompt.ts`: `buildPrompt`, for the `cover` kind.
 *
 * Order matters and is studio's: style first, composition second, the subject
 * third, prohibitions last. A prohibition placed before the subject is routinely
 * ignored by image models, which is how "no text" produces a picture with a word
 * in it.
 *
 * The subject is framed as what the illustration EVOKES "without depicting any
 * outcome". That clause is not decoration on a prediction market: the subject of
 * every one of these is a question about a future event, and asking a model to
 * depict an undecided outcome is asking it to answer the question in a picture
 * that then sits at the top of a page taking money on it.
 */
function promptFor(cover) {
  const subject = cover.trim()
  if (subject.length === 0) throw new Error('a cover generation has no subject to build a prompt from')
  return [
    coverStyle(ACCENT),
    COMPOSITION_COVER,
    `The subject this illustration evokes, without depicting any outcome: ${subject}`,
    NO_TEXT,
  ].join('\n\n')
}

/* ── the credential file ───────────────────────────────────────────────────── */

/**
 * `brand/generate.ts`'s `loadEnvFile`, same twelve lines and the same rules:
 * skip blanks and comments, split on the FIRST `=`, strip one layer of matching
 * quotes, and never overwrite a variable the environment already carries.
 *
 * It never echoes a value, and neither does anything downstream of it. The only
 * thing this function will ever print is a variable's NAME.
 */
function loadEnvFile(file) {
  if (!fs.existsSync(file)) return false
  for (const line of fs.readFileSync(file, 'utf8').split('\n')) {
    const trimmed = line.trim()
    if (trimmed.length === 0 || trimmed.startsWith('#')) continue
    const eq = trimmed.indexOf('=')
    if (eq <= 0) continue
    const key = trimmed.slice(0, eq).trim()
    let value = trimmed.slice(eq + 1).trim()
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1)
    }
    if (process.env[key] === undefined) process.env[key] = value
  }
  return true
}

/* ── the backend ───────────────────────────────────────────────────────────── */

/**
 * Anything long enough to be a credential, removed before a response body is
 * shown. `brand/backends.ts`'s `redact`, same shape.
 *
 * This is applied to what the ENDPOINT said, never to something this estate
 * holds — a redacting regex over our own configuration is the pattern that has
 * leaked a live value twice, and the rule is to print names instead. A remote
 * error envelope is a different thing: it is not ours, we cannot enumerate its
 * fields, and showing nothing at all would make a 400 unreadable.
 */
function redact(text) {
  return text.replace(/[A-Za-z0-9_-]{32,}/g, '[redacted]').replace(/\s+/g, ' ').trim().slice(0, 500)
}

function retryAfterSeconds(headers, body) {
  const header = Number(headers.get('retry-after') ?? '')
  const match = /retry after (\d+) second/i.exec(body)
  const fromBody = match ? Number(match[1]) : 0
  const seconds = Math.max(Number.isFinite(header) ? header : 0, fromBody)
  return seconds > 0 ? seconds + 1 : 0
}

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms))

/** How many 429s one image is allowed to absorb before the run gives up on it. */
const RATE_LIMIT_BUDGET = 8
const BLIND_BACKOFF_MS = 35_000
const PER_ASSET_TIMEOUT_MS = 900_000
const MAX_TRANSIENT = 3

/**
 * One image. Returns `{ bytes, attempts, costUnits }`.
 *
 * `bodyFor` is separated out so `--plan` can print the exact JSON that would go
 * on the wire without a credential being loaded at all — the parity discipline
 * from `brand/backends.ts`, where the body a backend WOULD send is exposed so it
 * can be asserted rather than assumed.
 */
function bodyFor(prompt) {
  return {
    model: MODEL,
    // Verbatim. The recorded prompt and the sent prompt are the same string, or
    // the manifest is a description of something that did not happen.
    prompt,
    size: `${WIDTH}x${HEIGHT}`,
    n: 1,
    quality: QUALITY,
  }
}

async function generate(prompt, config, signal) {
  const attempts = []
  let rateLimited = 0
  for (;;) {
    const started = Date.now()
    let response
    try {
      response = await fetch(config.url, {
        method: 'POST',
        headers: { 'content-type': 'application/json', 'api-key': config.apiKey },
        body: JSON.stringify(bodyFor(prompt)),
        signal,
      })
    } catch (err) {
      // NEVER the message and never the object: `fetch` embeds the full request
      // URL in it, and that URL names the resource. Class name and cause code
      // only. This is the rule from `never-print-a-caught-error-from-credential-
      // code`; it is not a style preference and it is not negotiable.
      const kind = err instanceof Error ? err.name : 'unknown'
      const code = err?.cause?.code ?? '-'
      attempts.push({ outcome: 'transport', detail: `${kind} (${code})`, durationMs: Date.now() - started })
      if (attempts.filter((a) => a.outcome === 'transport').length >= MAX_TRANSIENT) {
        throw new Error(`transport failure ${kind} (${code})`)
      }
      await sleep(2_000 * 2 ** attempts.length)
      continue
    }

    // Read once, in FULL. A success envelope is roughly 200,000 characters of
    // base64 and truncating it destroys the image that was paid for.
    const text = await response.text().catch(() => '')
    const durationMs = Date.now() - started

    if (response.status === 429) {
      rateLimited += 1
      const wait = retryAfterSeconds(response.headers, text) * 1_000 || BLIND_BACKOFF_MS
      attempts.push({ outcome: 'rate_limited', status: 429, detail: `waiting ${Math.round(wait / 1000)}s`, durationMs })
      if (rateLimited > RATE_LIMIT_BUDGET) throw new Error('rate limited beyond the per-image budget')
      await sleep(wait)
      continue
    }
    if (!response.ok) {
      attempts.push({ outcome: 'error', status: response.status, detail: redact(text), durationMs })
      // 400 and 401 do not get better by being retried; a 5xx might.
      if (response.status === 400 || response.status === 401 || response.status === 403) {
        throw new Error(`the endpoint refused the request with ${response.status}: ${redact(text)}`)
      }
      if (attempts.filter((a) => a.outcome === 'error').length >= MAX_TRANSIENT) {
        throw new Error(`the endpoint answered ${response.status}: ${redact(text)}`)
      }
      await sleep(2_000 * 2 ** attempts.length)
      continue
    }

    let payload
    try {
      payload = JSON.parse(text)
    } catch {
      throw new Error(`the endpoint answered 200 with a body that is not JSON (${text.length} characters)`)
    }
    const b64 = payload?.data?.[0]?.b64_json
    if (!b64) {
      // No `url` fallback, deliberately: `brand/backends.ts` records that this
      // endpoint returns base64 and a silent second shape is a second code path
      // nobody exercises.
      throw new Error(`the response carries no data[0].b64_json (${text.length} character envelope)`)
    }
    attempts.push({ outcome: 'ok', status: 200, detail: `ok, ${text.length} character envelope`, durationMs })
    return {
      bytes: Buffer.from(b64, 'base64'),
      attempts,
      costUnits: payload?.usage?.output_tokens ?? null,
    }
  }
}

/* ── the manifest ──────────────────────────────────────────────────────────── */

const MANIFEST_COMMENT =
  'Provenance for every committed Foresight cover. One entry per file, carrying the prompt it was ' +
  'generated from. Written by scripts/foresight-covers.mjs; do not edit by hand. coverCount is ' +
  'len(covers) by construction.'

function readManifest() {
  if (!fs.existsSync(MANIFEST)) return {}
  const parsed = JSON.parse(fs.readFileSync(MANIFEST, 'utf8'))
  const by = {}
  for (const entry of parsed.covers ?? []) by[entry.slug] = entry
  return by
}

function writeManifest(by) {
  const covers = Object.values(by).sort((a, b) => a.slug.localeCompare(b.slug))
  const document = {
    $comment: MANIFEST_COMMENT,
    generator: 'deploy/scripts/foresight-covers.mjs',
    provider: PROVIDER,
    endpoint: 'OpenAI, served by Azure AI Foundry',
    size: `${WIDTH}x${HEIGHT}`,
    accent: ACCENT,
    licence: LICENCE,
    disclosure:
      'Every image here is AI-generated. It is adopted at seed time by scripts/seed/foresight.mjs ' +
      'and uploaded to micro-studio as a public asset; the checksum foresight records is studio’s ' +
      'measurement of the uploaded bytes and is recorded, never verified.',
    coverCount: covers.length,
    updatedAt: new Date().toISOString(),
    covers,
  }
  fs.mkdirSync(ASSET_DIR, { recursive: true })
  fs.writeFileSync(MANIFEST, `${JSON.stringify(document, null, 2)}\n`)
}

const sha256 = (bytes) => crypto.createHash('sha256').update(bytes).digest('hex')

/** Width and height straight out of the PNG IHDR, so a delivered size is measured and not assumed. */
function pngSize(bytes) {
  if (bytes.length < 24 || bytes.readUInt32BE(12) !== 0x49484452) return null
  return `${bytes.readUInt32BE(16)}x${bytes.readUInt32BE(20)}`
}

/* ── the run ───────────────────────────────────────────────────────────────── */

function parseArgs(argv) {
  const value = (flag) => {
    const i = argv.indexOf(flag)
    return i >= 0 ? argv[i + 1] : undefined
  }
  const only = value('--only')
  // `Number(x) || Infinity` reads `--limit 0` as "no limit", which is the exact
  // opposite of what somebody typing zero means. Explicit finiteness check.
  const rawLimit = Number(value('--limit') ?? NaN)
  return {
    plan: argv.includes('--plan'),
    force: argv.includes('--force'),
    only: only ? only.split(',').map((s) => s.trim()).filter(Boolean) : null,
    limit: Number.isFinite(rawLimit) && rawLimit >= 0 ? rawLimit : Infinity,
  }
}

/** A loose match, because a 60-character slug is not something anybody types twice. */
function selected(slug, question, only) {
  if (!only) return true
  const haystack = `${slug} ${question.toLowerCase()}`
  return only.some((token) => haystack.includes(token.toLowerCase()))
}

async function main() {
  const args = parseArgs(process.argv.slice(2))
  if (args.force && !args.only) {
    console.error(
      'FAIL: --force needs --only. A blanket force regenerates every committed cover, including ' +
        'the nine whose prompts were never recorded and which cannot be reproduced. Name what you ' +
        'mean to replace.',
    )
    process.exit(1)
  }

  const manifest = readManifest()
  const work = []
  for (const q of FORESIGHT_QUESTIONS) {
    const slug = coverSlug(q.question)
    const file = path.join(ASSET_DIR, `${slug}.png`)
    const onDisk = fs.existsSync(file)
    const recorded = manifest[slug] !== undefined
    if (!selected(slug, q.question, args.only)) continue
    // The resume rule: on disk or in the manifest is done. `--force` overrides
    // it, and `--force` cannot be reached without `--only`.
    if ((onDisk || recorded) && !args.force) {
      // A file with no manifest entry gets one, describing exactly what is known
      // about it — which for the 2026-08-05 set does not include its prompt.
      if (onDisk && !recorded) {
        const bytes = fs.readFileSync(file)
        manifest[slug] = {
          slug,
          question: q.question,
          cover: q.cover,
          origin: 'pre-existing',
          provider: null,
          model: null,
          prompt: null,
          note:
            'Committed on 2026-08-05, before this manifest existed. It is FLUX 2 Pro art generated ' +
            'by hand against the live Azure resource; the exact prompt was not recorded at the time ' +
            'and is not reconstructible, so it is null rather than guessed. The sha256 and size ' +
            'below are measured from the committed bytes.',
          path: `assets/seed/foresight/${slug}.png`,
          size: pngSize(bytes),
          sha256: sha256(bytes),
          byteSize: bytes.length,
          licence: LICENCE,
          retries: 0,
        }
      }
      continue
    }
    work.push({ slug, file, question: q.question, cover: q.cover, prompt: promptFor(q.cover) })
  }

  const budgeted = work.slice(0, args.limit === Infinity ? undefined : args.limit)

  if (args.plan) {
    console.log(`${budgeted.length} cover(s) would be generated at ${WIDTH}x${HEIGHT} on ${PROVIDER}:`)
    for (const item of budgeted) {
      console.log(`\n── ${item.slug}\n   ${item.question}`)
      console.log(`   body: ${JSON.stringify({ ...bodyFor(item.prompt), prompt: `<${item.prompt.length} chars>` })}`)
    }
    console.log(`\n(--plan reads no credential and writes nothing. ${Object.keys(manifest).length} cover(s) already recorded or on disk.)`)
    return
  }

  // Backfilled entries for pre-existing files are worth keeping even on a run
  // that generates nothing.
  writeManifest(manifest)

  if (budgeted.length === 0) {
    console.log('every seeded question already has a committed cover — nothing to generate')
    return
  }

  const loaded = loadEnvFile(ENV_FILE)
  const endpoint = (process.env[ENDPOINT_VAR] ?? '').trim().replace(/\/+$/, '')
  const apiKey = (process.env[API_KEY_VAR] ?? '').trim()
  if (!endpoint || !apiKey) {
    // Names only. Never the values, never a prefix of them, never a length.
    console.error(
      `FAIL: ${ENDPOINT_VAR} and ${API_KEY_VAR} must both be set. They are read from ` +
        `${path.relative(MICRO, ENV_FILE)} (${loaded ? 'found' : 'NOT FOUND'}) or from the environment.`,
    )
    process.exit(1)
  }
  const config = { url: endpoint, apiKey }

  console.log(`generating ${budgeted.length} cover(s) at ${WIDTH}x${HEIGHT} on ${PROVIDER}`)
  let failures = 0
  for (const item of budgeted) {
    const previous = manifest[item.slug]
    const started = Date.now()
    try {
      const result = await generate(item.prompt, config, AbortSignal.timeout(PER_ASSET_TIMEOUT_MS))
      const size = pngSize(result.bytes)
      fs.mkdirSync(ASSET_DIR, { recursive: true })
      fs.writeFileSync(item.file, result.bytes)
      manifest[item.slug] = {
        slug: item.slug,
        question: item.question,
        cover: item.cover,
        origin: 'generated',
        provider: PROVIDER,
        model: MODEL,
        prompt: item.prompt,
        path: `assets/seed/foresight/${item.slug}.png`,
        requestedSize: `${WIDTH}x${HEIGHT}`,
        size,
        sha256: sha256(result.bytes),
        byteSize: result.bytes.length,
        // Measured on the bytes, never inherited from the vendor.
        c2pa: result.bytes.includes(Buffer.from('c2pa')),
        providerCostUnits: result.costUnits,
        licence: LICENCE,
        generatedAt: new Date().toISOString(),
        retries: previous ? (previous.retries ?? 0) + 1 : 0,
        attempts: result.attempts,
      }
      // After EVERY image, so an interrupt loses at most one.
      writeManifest(manifest)
      console.log(
        `  ok  ${item.slug} — ${size}, ${result.bytes.length} bytes, ` +
          `${Math.round((Date.now() - started) / 1000)}s`,
      )
    } catch (err) {
      // `generate` has already stripped anything that could carry a credential;
      // this message is one this file wrote, never the raw exception from a
      // fetch. See the file header.
      failures += 1
      console.error(`  FAIL ${item.slug} — ${err instanceof Error ? err.message : 'unknown failure'}`)
    }
  }
  console.log(`${budgeted.length - failures} generated, ${failures} failed`)
  if (failures > 0) process.exit(1)
}

await main()
