#!/usr/bin/env python3
"""Turn a release manifest into a compose overlay that pins every image.

    ./scripts/release-render.py ../org/releases/2026.08.1.yaml > compose/docker-compose.release.yml

WHY THIS EXISTS
---------------
micro-org already decides what a release IS, and that decision is good: a
manifest is a generated file naming exactly which image of each service is in a
release, `cfctl release` generates it from each repository's package.json version
and its git HEAD, a dirty checkout cannot be released because "an image tag
cannot name a working tree", and rollback is checking out the previous file.
None of that is re-invented here.

What did not exist is a CONSUMER. `cfctl release --verify` proves the images can
be pulled; nothing anywhere turned a manifest into a running system. So the
manifest satisfied "a release is a file" and not the sentence that matters in
17 §89 — "deployable and rollbackable BY MANIFEST ALONE". This is the piece that
makes that sentence true:

    deploy   = render(manifest N)   + docker compose up
    rollback = render(manifest N-1) + docker compose up

Those are the same command. That is the whole point: a rollback that is a
different procedure from a deploy is a procedure nobody has practised.

WHAT IT EMITS
-------------
An OVERLAY, not a replacement. The base compose file keeps owning environment,
dependency order, health checks and ports — the things that are properties of the
environment rather than of the release — and this overlay changes exactly one
thing per service: where the image comes from. `build:` is removed with `!reset`
so that a release deploy CANNOT silently fall back to building from a working
tree, which is the failure mode the manifest exists to eliminate.

Migrators are pinned to the same image as their service, deliberately. A migrator
running a different build from the service that then asserts its schema is the
oldest way to brick a deploy.
"""
import argparse
import pathlib
import re
import subprocess
import sys

parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
parser.add_argument("manifest", help="path to a release manifest (org/releases/<version>.yaml)")
parser.add_argument("--base", default="compose/docker-compose.estate.yml", help="the compose file the overlay applies to")
# ── WHICH ENVIRONMENT'S SERVICE LIST, WHICH IS NOT A DETAIL ──────────────────
#
# The base file renders a DIFFERENT SET OF SERVICES per environment: `faucet` is
# defined on testnet and not on mainnet (faucet/src/env.ts:63 fixes NETWORK to
# 'testnet' at compile time — mainnet EMBER is mined money and has no faucet).
#
# Without this, `config --services` below was always asked the MAINNET question,
# so a testnet render decided `faucet` "is not in this environment" and dropped
# its pin. A dropped pin does not fail: the base file's `build:` survives, and
# the release deploy silently builds faucet from whatever is in the working tree
# — which is the single failure mode this whole script exists to eliminate, and
# it would have been introduced by the script itself.
parser.add_argument("--env-file", help="passed to `docker compose` so the base service list is the one THIS environment defines")
parser.add_argument("--out", help="write here instead of stdout")
args = parser.parse_args()

manifest_path = pathlib.Path(args.manifest)
if not manifest_path.exists():
    sys.exit(f"FAIL: no manifest at {manifest_path}")

# --------------------------------------------------------------------------
# Parse exactly the shape cfctl's renderManifest emits, and nothing else.
#
# This mirrors org/tools/cfctl.ts parseManifest on purpose, including its
# reasoning: "a manifest that is not exactly this shape was not generated by
# cfctl and should not be deployed." A tolerant parser here would accept a
# hand-written file, and a hand-written manifest is the drift the format exists
# to prevent.
# --------------------------------------------------------------------------
text = manifest_path.read_text()
version = ""
services = []
absent = []
section = None
current = None

for raw in text.split("\n"):
    line = raw.rstrip()
    if not line or line.lstrip().startswith("#"):
        continue
    if line.startswith("version:"):
        version = line[len("version:"):].strip().strip('"')
        continue
    if line.startswith("generated:") or line.startswith("generator:"):
        continue
    if line == "services:":
        if current:
            services.append(current)
            current = None
        section = "services"
        continue
    if line == "absent:":
        if current:
            services.append(current)
            current = None
        section = "absent"
        continue
    if section == "absent" and line.startswith("  - "):
        absent.append(line[4:].strip())
        continue
    if section == "services":
        if line.startswith("  - "):
            if current:
                services.append(current)
            current = {}
        body = re.sub(r"^ {2}(- )?", "", line)
        body = re.sub(r"^ {2}", "", body)
        if ":" in body and current is not None:
            key, _, value = body.partition(":")
            current[key.strip()] = value.strip().strip('"')
if current:
    services.append(current)

if not version:
    sys.exit(f"FAIL: {manifest_path} names no version. Refusing to render a release that cannot be named.")
if not services:
    # The same refusal cfctl's --verify makes: "'all 0 images exist' is a true
    # sentence and a useless one."
    sys.exit(f"FAIL: {manifest_path} names no images. A manifest that pins nothing is not a release.")

# --------------------------------------------------------------------------
# What the environment actually defines. Asking compose rather than parsing the
# YAML: an overlay naming a service the base does not define would not override
# anything, it would CREATE a container with an image and no environment, no
# health check and no dependencies — which would start, and would be wrong.
# --------------------------------------------------------------------------
base = pathlib.Path(args.base)
if not base.exists():
    sys.exit(f"FAIL: no base compose file at {base}")
config_cmd = ["docker", "compose"]
if args.env_file:
    config_cmd += ["--env-file", args.env_file]
config_cmd += ["-f", str(base), "config", "--services"]
try:
    proc = subprocess.run(config_cmd, capture_output=True, text=True, check=True)
except FileNotFoundError:
    sys.exit("FAIL: docker is not available, so the base service list cannot be read. Refusing to guess it.")
except subprocess.CalledProcessError as exc:
    sys.exit(f"FAIL: `docker compose config --services` failed:\n{exc.stderr}")
defined = {s.strip() for s in proc.stdout.split("\n") if s.strip()}

lines = [
    "# GENERATED by scripts/release-render.py — do not hand-edit.",
    f"# Release:  {version}",
    f"# Manifest: {manifest_path}",
    "#",
    "# Pins every service to the image the manifest names, and REMOVES `build:` so",
    "# that a release deploy cannot fall back to building from a working tree.",
    "#",
    "#   deploy:   docker compose -f compose/docker-compose.estate.yml -f THIS up -d",
    "#   rollback: render the previous manifest and run the same command.",
    "",
    "services:",
]

pinned, skipped, missing = [], [], []
for svc in services:
    name = svc.get("name", "")
    image, tag = svc.get("image", ""), svc.get("tag", "")
    if not name or not image or not tag:
        sys.exit(f"FAIL: {manifest_path} has an entry missing name, image or tag: {svc!r}")
    # A web or ops deployable is in the manifest but is not part of this
    # environment. Recorded, not silently dropped.
    targets = [t for t in (name, f"{name}-migrate") if t in defined]
    if not targets:
        skipped.append(name)
        continue
    for target in targets:
        lines.append(f"  {target}:")
        lines.append(f"    image: {image}:{tag}")
        # !reset is how compose deletes an inherited value rather than merging
        # it. Without it the base file's `build:` survives and compose would
        # rebuild from the working tree, which is exactly what a pinned release
        # must never do.
        lines.append("    build: !reset null")
        pinned.append(target)

# A service this environment runs that the release does not name. This is the
# `absent` case, and it is the one the manifest format calls out by name: "a
# manifest with a silent hole is how a service gets left on an old image while
# everything around it moves."
manifest_names = {s.get("name", "") for s in services}
for name in sorted(defined):
    root = name[: -len("-migrate")] if name.endswith("-migrate") else name
    if root in manifest_names or root == "postgres":
        continue
    missing.append(name)

lines.append("")
lines.append(f"# pinned {len(pinned)} container(s) from {len(services)} manifest entries")
if skipped:
    lines.append(f"# in the manifest but NOT in this environment: {', '.join(sorted(skipped))}")
if absent:
    lines.append(f"# the manifest lists as absent: {', '.join(absent)}")
if missing:
    lines.append("#")
    lines.append("# WARNING — this environment defines these and the release does not name them.")
    lines.append("# They keep whatever image they already had, which is the silent hole the")
    lines.append("# manifest format exists to prevent:")
    for name in missing:
        lines.append(f"#   {name}")

out = "\n".join(lines) + "\n"
if args.out:
    pathlib.Path(args.out).write_text(out)
    print(f"wrote {args.out}: {len(pinned)} container(s) pinned for release {version}", file=sys.stderr)
else:
    sys.stdout.write(out)

if missing:
    print(f"\nWARNING: {len(missing)} container(s) in this environment are not named by release {version}: {', '.join(missing)}", file=sys.stderr)
